/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int OPEN_PAR = 7;
  /** RegularExpression Id. */
  int CLOSE_PAR = 8;
  /** RegularExpression Id. */
  int OPERADOR = 9;
  /** RegularExpression Id. */
  int COMPARADOR = 10;
  /** RegularExpression Id. */
  int PREDID = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<NUMBER>",
    "<VARIABLE>",
    "\"(\"",
    "\")\"",
    "<OPERADOR>",
    "<COMPARADOR>",
    "<PREDID>",
    "\",\"",
    "\".\"",
    "\":\"",
  };

}
